services:
  - type: web
    name: visualmusic-backend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg build-essential
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
