name: Test Backend API

on:
  workflow_dispatch:  # permite lanzarlo manualmente desde GitHub

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run backend test
        run: python test_backend.py
